# Generated by Django 5.1.3 on 2024-11-24 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arhive', 'Archive')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('non', 'Non'), ('analyst', 'Analyst'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('project-manager', 'Project-manager'), ('designer', 'Designer'), ('conceptologist', 'Conceptologist'), ('devops', 'Devops'), ('tester', 'Tester')], default='non', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(related_name='participant_projects', through='projects.ProjectParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
