# Generated by Django 5.1.3 on 2024-11-24 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status_projectparticipant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='role',
            field=models.CharField(choices=[('non', 'Non'), ('analyst', 'Analyst'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('project-manager', 'Project-manager'), ('designer', 'Designer'), ('conceptologist', 'Conceptologist'), ('devops', 'Devops'), ('tester', 'Tester')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
