# Generated by Django 5.1.3 on 2024-11-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_status_roles_delete_projectparticipant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
