# Generated by Django 5.1.3 on 2024-11-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arhive', 'Archive')], default='active', max_length=20),
        ),
    ]
